baseURL = "https://dzung.org/"
languageCode = "en-us"
title = "Dzung"
theme = "contrast-hugo"

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
